baseURL = "/"
languageCode = "zh-cn"
title = "SportsHub.AI"
theme = "hugo-saasify-theme"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

# 语言定义

[languages.en]
  weight = 2
  languageName = "English"
  contentDir = "content/en"
  lang = "en"

  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/en/"
    weight = 1

  [[languages.en.menu.main]]
    identifier = "company"
    name = "Company"
    url = "/en/company/"
    weight = 2

  [[languages.en.menu.main]]
  identifier = "products"
  name = "Products"
  weight = 3

  [[languages.en.menu.main]]
  parent = "products"
  name = "Swish App - AI-driven basketball training"
  url = "/en/products/swish-app/"
  weight = 1

  [[languages.en.menu.main]]
  parent = "products"
  name = "Video Editor"
  #url = "/en/products/video-editor/"
  weight = 2

  [[languages.en.menu.main]]
  parent = "products"
  name = "Intelligent Football Wearable Devices"
  #url = "/en/products/football-wearable/"
  weight = 3


  [[languages.en.menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/en/contact/"
    weight = 4


[languages.zh]
  weight = 1
  languageName = "简体中文"
  contentDir = "content/zh"
  lang = "zh"

  [[languages.zh.menu.main]]
    identifier = "home"
    name = "首页"
    url = "/zh/"
    weight = 1

  [[languages.zh.menu.main]]
    identifier = "company"
    name = "公司介绍"
    url = "/zh/company/"
    weight = 2
    
  
  [[languages.zh.menu.main]]
  identifier = "products"
  name = "产品简介"
  weight = 3

  [[languages.zh.menu.main]]
  parent = "products"
  name = "空心球App-AI驱动的智能篮球训练"
  url = "/zh/products/swish-app/"
  weight = 1

  [[languages.zh.menu.main]]
  parent = "products"
  name = "视频剪辑"
  #url = "/zh/products/video-editor/"
  weight = 2

  [[languages.zh.menu.main]]
  parent = "products"
  name = "智能足球穿戴装备"
  #url = "/zh/products/football-wearable/"
  weight = 3

  [[languages.zh.menu.main]]
    identifier = "contact"
    name = "联系我们"
    url = "/zh/contact/"
    weight = 4

# Required Features
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true
enableGitInfo = true

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true

# Required Markup Configuration
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Theme Parameters (共享参数，可在 zh/en 各自语言内容中重写)
[params]
  description = "Your site description"
  author = "Your Name"
  logo = "/images/shai-logo.svg"

  googleAnalytics = "G-XXXXXXXXXX"

  [params.header]
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"

    [params.header.logo]
      src = "/images/shai-logo.svg"

    #[params.header.buttons]
    #  [params.header.buttons.getStarted]
    #    text = "联系我们"
    #    url = "mailto:business@sportshub-ai.com"

  [params.cta]
    enable = true
    title = "准备开始了吗？"
    description = "加入使用我们平台的企业"
    [params.cta.primary_button]
      text = "免费开始"
      url = "#"
    [params.cta.secondary_button]
      text = "预约演示"
      url = "#"

  [params.social]
    # linkedin = "https://linkedin.com/in/yourusername"
    # twitter = "https://twitter.com/yourusername"
    # github = "https://github.com/SportsHub-AI"
