baseURL = "/"
languageCode = "zh-cn"
title = "SportsHub.AI"
theme = "hugo-saasify-theme"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

# 语言定义
[languages]

  [languages.zh]
    languageName = "简体中文"
    contentDir = "content/zh"
    lang = "zh-cn"
    weight = 1

  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    lang = "en"
    weight = 2

# Required Features
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true
enableGitInfo = true

# Required Module Configuration
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

# Required Build Configuration
[build]
  writeStats = true

# Required Markup Configuration
[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Theme Parameters (共享参数，可在 zh/en 各自语言内容中重写)
[params]
  description = "Your site description"
  author = "Your Name"
  logo = "/images/shai-logo.svg"

  googleAnalytics = "G-XXXXXXXXXX"

  [params.header]
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"

    [params.header.logo]
      src = "/images/shai-logo.svg"

    [params.header.buttons]
      [params.header.buttons.getStarted]
        text = "联系我们"
        url = "mailto:bussiness@sportshub-ai.com"

  [params.cta]
    enable = true
    title = "准备开始了吗？"
    description = "加入使用我们平台的企业"
    [params.cta.primary_button]
      text = "免费开始"
      url = "#"
    [params.cta.secondary_button]
      text = "预约演示"
      url = "#"

  [params.social]
    # linkedin = "https://linkedin.com/in/yourusername"
    # twitter = "https://twitter.com/yourusername"
    # github = "https://github.com/SportsHub-AI"
